# general configuration
url: https://kapc.io

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/lombard.jpg"
  # author will appear under the avatar (optional)
  author: "Will Kapcio"
  # William Kapcio
  description: "Will Kapcio's personal site"
  # tagline will appear under the title (optional)
  tagline: "@WhiskeyKiloSec"
  # location will appear under tagline (optional)
  location: "New York, NY"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "whiskeykilosec"
  # other social
  social:
    name: Will Kapcio
    links:
      - mailto:will@kapc.io
      - https://www.linkedin.com/in/wkapcio
      - https://twitter.com/whiskeykilosec
      - https://hackerone.com/whiskeykilosec
      - https://github.com/whiskeykilosec
      - https://www.hackthebox.eu/profile/245928

  # seo
  seo:
    name: William Kapcio
    type: Person
    links:
      - mailto:will@kapc.io
      - https://www.linkedin.com/in/wkapcio
      - https://twitter.com/whiskeykilosec
      - https://hackerone.com/whiskeykilosec
      - https://github.com/whiskeykilosec
      - https://www.hackthebox.eu/profile/245928

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag